api/web/router.ex
defmodule OpenStock.Router do
  use OpenStock.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticated do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug OpenStock.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["html", "json-api"]
  end

  scope "/", OpenStock do
    pipe_through [:api]

    get "/", PageController, :index
    get "/companies/:ticker", CompanyController, :show

    resources "/users", UserController, only: [:show, :new, :create]

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/watchlists", WatchlistController, only: [:create, :index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", OpenStock do
  #   pipe_through :api
  # end
end

api/web/views/layout_view.ex
defmodule OpenStock.LayoutView do
  use OpenStock.Web, :view
end

api/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Open Stock</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>

  <body>
    <header>
      <div id="open-stock-wrapper">
        <div id="open-stock">Open Stock</div>
        <div id="navbar" class="pull-right">
          <%= if @current_user do %>
            <li><%= link @current_user.email, to: "/users/#{@current_user.id}" %></li>
            <li>
              <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
          <% end %>
        </div>
      </div>
    </header>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>