api/web/router.ex
defmodule OpenStock.Router do
  use OpenStock.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticated do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug OpenStock.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["html", "json-api"]
  end

  scope "/", OpenStock do
    pipe_through [:api]

    get "/", PageController, :index
    get "/companies/:ticker", CompanyController, :show

    resources "/users", UserController, only: [:show, :new, :create]

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/watchlists", WatchlistController, only: [:create, :index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", OpenStock do
  #   pipe_through :api
  # end
end

api/web/models/watchlist.ex
defmodule OpenStock.Watchlist do
  use OpenStock.Web, :model

  schema "watchlists" do
    field :title, :string
    field :description, :string
    belongs_to :user, OpenStock.User

    many_to_many :companies, OpenStock.Company, join_through: "companies_watchlists"

    timestamps()
  end

  @required_fields ~w(title)a

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields)
    |> validate_required(@required_fields)
    |> assoc_constraint(:user)
  end
end

api/web/controllers/watchlist_controller.ex
defmodule OpenStock.WatchlistController do
  use OpenStock.Web, :controller

  alias OpenStock.Watchlist
  alias OpenStock.User
  alias OpenStock.Company

  # def action(conn, _) do
  #   apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
  # end

  def create(conn, %{"watchlist" => watchlist_params}, current_user) do
    changeset = Watchlist.changeset(%Watchlist{}, watchlist_params)
    |> Ecto.Changeset.put_assoc(:user, current_user)
    Repo.insert!(changeset)
    conn
    |> redirect(to: "/users/#{current_user.id}")
  end

  def index(conn, _params) do
    query = from w in Watchlist,
      join: c in assoc(w, :companies),
      where: w.user_id == 11,
      preload: [:companies],
      select: map(w, [:title, :description, :id, companies: [:ticker, :name, :sector, :short_description]])

    watchlists = Repo.all(query)

    json conn, %{ watchlists: Repo.all(query) }
  end

  # def update(conn, params) do
  #   watchlist = Repo.get(Watchlist, id)
  #   changeset = Ecto.Changeset.change watchlist, params
  # end
end

api/web/views/watchlist_view.ex
defmodule OpenStock.WatchlistView do
  use OpenStock.Web, :view
end

api/web/templates/watchlist/index.html.eex
<div class="create-watchlist-form col-sm-6">
	<h3>Create Watchlist</h3>
	<%= form_for @conn, watchlist_path(@conn, :create), [as: :watchlist], fn f -> %>
		<div>
			<label>Title</label><br>
			<%= text_input f, :title, class: "form-control" %>
		</div>
		<div>
			<label>Description</label>
			<%= textarea f, :description, class: "form-control" %>
		</div>
		<div class="btn-wrapper">
			<%= submit "Create Watchlist", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

<div class="col-sm-6"
	<%= for watchlist <- @watchlists do %>
    <p><%= watchlist.title %></p>
	<% end %>
</div>

<style>
	.btn-wrapper .btn {
		margin-top: 10px;
	}
</style>